windows_container:
  image: cirrusci/windowsservercore:2019
  os_version: 2019

task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  install_script: npm install -g cordova
  build_script: cordova build windows