windows_container:
  image: cirrusci/windowsservercore:cmake
  os_version: 2019

task:
  install_vsstudio_script: |
    choco install visualstudio2017community --params "--add Microsoft.VisualStudio.Workload.Universal --add Microsoft.VisualStudio.Component.Windows10SDK.10240 --add Microsoft.VisualStudio.Workload.WebBuildTools --add Microsoft.Net.Core.Component.SDK.2.1 --add Microsoft.VisualStudio.Workload.WebCrossPlat" --force -y
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild"

  msbuild_script: |
    "C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" -latest -products "*" -requires Microsoft.Component.MSBuild -property installationPath
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild"
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0"
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"

  msbuild2_script: |
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\"
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\VisualStudio"
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\VisualStudio\v15.0"
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\VisualStudio\v15.0\JavaScript"

  foo_script: |
    choco install nodejs -y
    refreshenv
    npm ci
    npm install -g cordova
    set MSBUILDDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
    cordova build windows --verbose
    cordova run windows --verbose
