windows_container:
  image: cirrusci/windowsservercore:2019
  os_version: 2019

task:
  install_script: |
    choco install nodejs -y
    refreshenv
    npm ci
    npm install -g cordova
    cordova build windows --verbose
  build_script: cordova build windows --verbose