windows_container:
  image: cirrusci/windowsservercore:cmake
  os_version: 2019

task:
  install_vsstudio_script: |
    choco install visualstudio2017community --package-parameters "--add Microsoft.VisualStudio.Workload.Universal --add Microsoft.VisualStudio.Component.Windows10SDK.10240 --add Microsoft.VisualStudio.Workload.WebBuildTools --add Microsoft.VisualStudio.Workload.NetCoreTools --add Microsoft.VisualStudio.Component.Windows10SDK.16299.UWP" --force -y
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild"
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft"
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio"
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0"
    dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\JavaScript"

  foo_script: |
    choco install nodejs -y
    refreshenv
    npm ci
    npm install -g cordova
    set MSBUILDDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
    cordova build windows --verbose
    cordova run windows --verbose
