windows_container:
  image: cirrusci/windowsservercore:cmake
  os_version: 2019

task:
  install_vsstudio_workloads_script: |
    choco install visualstudio2017-workload-universal -y
    choco install visualstudio2017-workload-webcrossplat -y

  foo_script: |
    choco install nodejs -y
    refreshenv
    npm ci
    npm install -g cordova
    set MSBUILDDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
    cordova build windows --verbose
    cordova run windows --verbose
