windows_container:
  image: cirrusci/windowsservercore:2019
  os_version: 2019

task:
  install_script: |
    choco install nodejs
    npm ci
    npm install -g cordova
  build_script: cordova build windows