os: windows
language: node_js
node_js: 10

install:
  - npm install -g cordova
  - npm install

before_script: 
  - export PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/Installer/"
  - export MSVC=$(vswhere -latest -products "*" -requires Microsoft.Component.MSBuild -property installationPath)
  - export MSVC=$(echo /$MSVC | sed -e 's/\\/\//g' -e 's/://')
  - export MSBUILDDIR="$MSVC/MSBuild/15.0/Bin/"

script:
  - cordova build windows --verbose
  - cordova run windows --verbose
