trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g cordova
  displayName: 'npm install + cordova'

- script: |
    echo "execute msbuild"
    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\msbuild.exe" -version -nologo
    echo "SET MSBUILDDIR"
    SET MSBUILDDIR="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\"
    echo "cordova build windows"
    cordova build windows --verbose
  displayName: 'cordova build windows'
