trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g cordova
    npm install
  displayName: 'npm install'

- script: |
    cordova build windows
  displayName: 'cordova build windows'
