trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g cordova
  displayName: 'npm install + cordova'

- script: |
    cordova build windows
  displayName: 'cordova build windows --verbose'
